service: getRecipes
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  region: sa-east-1

custom:
  esbuild:
    target: node20
    minify: true

functions:
  getRecipes:
    handler: src/index.handler
    environment:
      RECIPES_API_KEY: 789f0155-07f7-442e-baf5-acdf602b9890
    events:
      - httpApi:
          path: /recipes
          method: POST
